
CREATE EFI_SERIAL_IO_PROTOCOL_GUID 0xBB25CF6F L, 0xF1D4 W, 0x11D2 W, 0x9A C, 0x0C C, 0 C, 0x90 C, 0x27 C, 0x3F C, 0xC1 C, 0xFD C,

VARIABLE SER_ID

SER_ID  0
EFI_SERIAL_IO_PROTOCOL_GUID	BOOTSERV LocateProtocol @  3XSYS THROW

: SER_EMIT >R RP@ 1 SER_ID @ WRITE-FILE DROP RDROP ;

: SER_DO ( cfa -- )
  ['] EMIT DEFER@ >R
  ['] SER_EMIT TO EMIT
  ['] EXECUTE CATCH
  R> TO EMIT
  THROW
;

: SER>  ['] INTERPRET SER_DO ;
