
: A7\ POSTPONE \ ; IMMEDIATE
: A9\ ; IMMEDIATE
: MC! C! ;
: MC@ C@ ;
: MW! W! ;
: MW@ W@ ;
:  M!  ! ;
:  M@  @ ; 
: M0! 0! ;
: M+! +! ;
:  M+  + ; 
: M-/ / ;
: MNEGATE NEGATE ; 
: MOVER OVER ;
: MAND AND ;
: MCR CR ;
: MH. H. ;
: MHERER H. ;
: M_. . ;
: M.S .S ;
: MDEPTH DEPTH ;
: MHEX HEX ;
: MKEY KEY ;
\+ KEY? : MKEY? KEY? ;
: MEXECUTE EXECUTE ;
: MWDS WORDS ;
: MCMOVE CMOVE ;
: MFILL FILL ;
: \ZEOF ;
: M\EOF \EOF ;
\ : MCHAR CHAR ;
\- ANDC : ANDC INVERT AND ;

: SYNONYM  HERE >R DP ! HEADER R> DP ! ;

$804040e8 VALUE 'FSTART
'FSTART $800000 + VALUE 'FGLOB
$90000000 VALUE 'FDATA

: MREAD-FILE READ-FILE ;

\- BREAK : BREAK  POSTPONE EXIT POSTPONE THEN ; IMMEDIATE

[IFNDEF] /*
: /*  ( -- )
  BEGIN
    PARSE-NAME DUP 0=
    IF  NIP  REFILL   0= IF DROP TRUE THEN
    ELSE  S" */" COMPARE 0=  THEN
  UNTIL
; IMMEDIATE
[THEN]

0 VALUE SSBB

\- DUPCOUTSET : DUPCOUTSET DUP TO H-STDOUT ;
\- COUTRESTORE : COUTRESTORE ( H-STDOUT CLOSE-FILE DROP)  1 TO H-STDOUT ;


\ REQUIRE <SIGN>	lib/include/float0.f

VECT	LOADER_SYNCHRONIZE
VECT	LOADER_LOAD
VECT	LOADER_GO

0 VALUE THS_ID
: THS_CREATE
    R/W CREATE-FILE THROW TO THS_ID
;

: THS_CLOSE
  THS_ID 0= IF BREAK
  THS_ID   CLOSE-FILE THROW 
 0 TO THS_ID
;

: THS>
  THS_ID DUPCOUTSET DROP INTERPRET
 COUTRESTORE
;

: DO_THS ( cfa -- )
   THS_ID 0= IF DROP BREAK
  THS_ID DUPCOUTSET DROP  EXECUTE
 COUTRESTORE
;
[IFNDEF] CHAR-UPPERCASE
: CHAR-UPPERCASE ( c -- c1 )
  DUP [CHAR] a [CHAR] z 1+ WITHIN IF 32 - EXIT THEN
;
[THEN]

: UP_TYPE ( adr len  -- )
  0 ?DO COUNT
  DUP  '\' = IF '\' EMIT THEN
 CHAR-UPPERCASE EMIT
	 LOOP DROP ;

0 VALUE TLASTFLG

: $THS (  adr len -- )
   THS_ID 0= IF 2DROP BREAK
 
 ['] TYPE DO_THS
;

: $ETHS (  c -- )
   THS_ID 0= IF 2DROP BREAK
 ['] EMIT DO_THS
;

: $UPTHS (  adr len -- )
   THS_ID 0= IF 2DROP BREAK
 ['] UP_TYPE DO_THS
;

VECT VGTYPE

' UP_TYPE TO VGTYPE

: $:THS
 TLASTFLG 0 (D.) TYPE 0 TO TLASTFLG
 CR TYPE
 '`' EMIT
  >IN M@ PARSE-NAME UP_TYPE >IN M!
 '`' EMIT 
 ',' EMIT
  >IN M@ PARSE-NAME VGTYPE >IN M!
 S" ,0x" TYPE  CURSTR @ H.
 ',' EMIT
;

: C$:THS ( n adr len -- n )
 TLASTFLG 0 (D.) TYPE 0 TO TLASTFLG
 CR TYPE

 '`' EMIT
  >IN M@ PARSE-NAME UP_TYPE >IN M!
 '`' EMIT 
 ',' EMIT

  DUP
   DUP  'FSTART
 - 0xFFFFFF U<
  IF  'FSTART -  ." fimg+"
  THEN
  	'0' EMIT 'x' EMIT
	   H.
 S" ,0x" TYPE  CURSTR @ H.
 ',' EMIT
;

: :#THS THS_ID 0= IF BREAK
  S" F_BUILD " ['] $:THS DO_THS ;

: VAR:THS THS_ID 0= IF BREAK
  S" CONSTANT_W " ['] C$:THS DO_THS ;

: CON:THS THS_ID 0= IF BREAK
  S" CONSTANT_W " ['] C$:THS DO_THS ;

: THS::
   TLASTFLG 0 (D.)  ['] TYPE DO_THS 0 TO TLASTFLG  ['] CR DO_THS	
  S" S_VIEW_PATH 'B:\xx'" $THS
  ['] CR DO_THS ['] CR DO_THS
 ;

VECT G_INCLUDED

VARIABLE TH_N_LINK

: GINCLUDED
  2DUP 2>R
     G_INCLUDED 
   TLASTFLG 0 (D.)  ['] TYPE DO_THS 0 TO TLASTFLG  ['] CR DO_THS
  S" S_VIEW_PATH 'ForthSrc/" $THS  2R> $THS ''' $ETHS
  ['] CR DO_THS ['] CR DO_THS
  S" VIEW_S " $THS
;

