
: A7\ POSTPONE \ ; IMMEDIATE
: A9\ ; IMMEDIATE
: MC! C! ;
: MC@ C@ ;
: MW! W! ;
: MW@ W@ ;
:  M!  ! ;
:  M@  @ ; 
: M0! 0! ;
: M+! +! ;
:  M+  + ; 
: M-/ / ;
: MNEGATE NEGATE ; 
: MOVER OVER ;
: MAND AND ;
: MCR CR ;
: MH. H. ;
: MHERER H. ;
: M_. . ;
: M.S .S ;
: MDEPTH DEPTH ;
: MHEX HEX ;
: MKEY KEY ;
\+ KEY? : MKEY? KEY? ;
: MEXECUTE EXECUTE ;
: MWDS WORDS ;
: MCMOVE CMOVE ;
: MFILL FILL ;
: \ZEOF ;
: M\EOF \EOF ;
\ : MCHAR CHAR ;
\- ANDC : ANDC INVERT AND ;

: SYNONYM  HERE >R DP ! HEADER R> DP ! ;

$804040e8 VALUE 'FSTART
'FSTART $800000 + VALUE 'FGLOB
$90000000 VALUE 'FDATA

: MREAD-FILE READ-FILE ;

\- BREAK : BREAK  POSTPONE EXIT POSTPONE THEN ; IMMEDIATE

[IFNDEF] /*
: /*  ( -- )
  BEGIN
    PARSE-NAME DUP 0=
    IF  NIP  REFILL   0= IF DROP TRUE THEN
    ELSE  S" */" COMPARE 0=  THEN
  UNTIL
; IMMEDIATE
[THEN]

0 VALUE SSBB

\- DUPCOUTSET : DUPCOUTSET DUP TO H-STDOUT ;
\- COUTRESTORE : COUTRESTORE ( H-STDOUT CLOSE-FILE DROP)  1 TO H-STDOUT ;

